# Example of config for code2vec approach

root_dir: "/lmsignatures"
feat_dir: "/lmsignatures/data/spn/images" # preprocessed images
pbb_dir: "/lmsignatures/data/spn/bbox" # proposed nodule ROIs
labels: "/lmsignatures/data/spn/spn_signatures.csv" # input tabular data (see README)
codes: "/lmsignatures/data/spn/spn_codes.csv" # ICD codes (see README)
icd10_embedding: "/lmsignatures/code_embedding.json" # ICD embedding (see README)
pretrained_mae: null
pretrained_model: "/lmsignatures/models/tdc2v_imageehr/best_model.pth" # optional

dataset: 'PaddedLongC2VDataset'

random_seed: 1106
val_fraction: 0.15
checkpoint: null
topk: 5
time_length: 2

# Model Params
freeze_img_emb: False # freeze nodule embedding
freeze_ehr_emb: False # freeze ica embeddings
model_class: "IcaRoiTD"
feat_dim: 320
code_dim: 100
time_enc: "AbsTimeEncoding"
embedding_dim: 320
dim_head: 64
depth: 4
heads: 4
mlp_dim: 124
qkv_bias: False
dropout: 0.1

# Pretraining params
batch_size: 25
epochs: 3000
lr: 0.00000001 # peak learning rate
schedule: "Cosine"
warmup_steps: 200
val_interval: 5

checkpoint_interval: 20
stop_agg: 500
stop_delta: 0.2
