# Example of config for latent clinical signatures approach

root_dir: "/lmsignatures"
feat_dir: "/lmsignatures/data/imageehr/images/" # preprocessed images
pbb_dir: "/lmsignatures/data/imageehr/bbox" # proposed nodule ROIs
labels: "/lmsignatures/data/imageehr/imageehr_signatures.csv" # input tabular data with clinical signatures (see README)
codes: null
icd10_embedding: null
pretrained_mae: null
pretrained_model: "/lmsignatures/models/tdsig_nlst/best_model.pth" # pretrained moded (optional)

dataset: 'PaddedLongICADataset'

random_seed: 1105
val_fraction: 0.15
checkpoint: null
topk: 5
time_length: 1

# Model Params
freeze_img_emb: False # freeze nodule embedding
freeze_ehr_emb: False # freeze ica embeddings
model_class: "IcaRoiTD"
feat_dim: 320 # size of convolutional embedding
code_dim: 2000 # number of clinical signatures
time_enc: "AbsTimeEncoding"
embedding_dim: 320 # size of token embedding
dim_head: 64 # size of attention head
depth: 4 # number of transformer blocks
heads: 4 # number of attention heads
mlp_dim: 124 # size of MLP in transformer block
qkv_bias: False
dropout: 0.1

# Pretraining params
batch_size: 25
epochs: 3000
lr: 0.0000001 # peak learning rate
schedule: "Cosine"
warmup_steps: 200
val_interval: 5 # perform validation every 5 global steps

checkpoint_interval: 20 # save model every 20 epochs
stop_agg: 100 # aggregation range for computing the running median
stop_delta: 0.2 # delta between current median and previous median