# training on NLST scans with nodules only

root_dir: "/lmsignatures"
feat_dir: "/lmsignatures/data/nlst/images/"
pbb_dir: "/lmsignatures/data/nlst/bbox"
labels: "/lmsignatures/data/nlst/nlst.csv"
codes: null
icd10_embedding: null
pretrained_mae: null
pretrained_model: null

dataset: 'PaddedLongNLSTDataset'

random_seed: 1105
val_fraction: 0.15
checkpoint: null
topk: 5
time_length: 1

# Model Params
freeze_img_emb: False # freeze nodule embedding
freeze_ehr_emb: False # freeze ica embeddings
model_class: "IcaRoiTD"
feat_dim: 320
code_dim: 2000
time_enc: "AbsTimeEncoding"
embedding_dim: 320
dim_head: 64
depth: 4
heads: 4
mlp_dim: 124
qkv_bias: False
dropout: 0.1

# Pretraining params
batch_size: 6
epochs: 3000
lr: 0.000001 # peak learning rate
schedule: "Cosine"
warmup_steps: 200
val_interval: 100

checkpoint_interval: 2
stop_agg: 100
stop_delta: 0.5